# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
api:
    prefix: /api
    resource: "@ApiBundle/Resources/config/routing.yml"
    
site_interface:
    prefix: /
    resource: "@SiteInterfaceBundle/Resources/config/routing.yml"
    
admin_interface:
    prefix: /admin
    resource: "@AdminInterfaceBundle/Resources/config/routing.yml"

superadmin_api:
    prefix: /superadmin/api
    resource: "@SuperAdminApiBundle/Resources/config/routing.yml"
    
superadmin_interface:
    prefix: /superadmin
    resource: "@SuperAdminInterfaceBundle/Resources/config/routing.yml"
    