api_common:
    prefix: /common
    resource: "@ApiBundle/Resources/config/routing/common.yml"
    
api_remotedataaccess:
    prefix: /remotedataaccess
    resource: "@ApiBundle/Resources/config/routing/remoteDataAccess.yml"