SuperAdmin\CoreBundle\Entity\Field:
    properties:
        type:
            - NotBlank: ~
            - Length: 
                max:    55
        label:
            - NotBlank: ~
            - Length: 
                min:    5
                max:    255
        name:
            - NotBlank: ~
            - Length: 
                min:    5
                max:    255
        
SuperAdmin\CoreBundle\Entity\Object:
    properties:
        name:
            - NotBlank: ~
            - Length: 
                min:    5
                max:    55
                