superadmin_interface_object_crud:
    pattern:  /crud
    defaults: { _controller: SuperAdminInterfaceBundle:Object:crud }
    methods: [GET]
    
superadmin_interface_object_edit:
    pattern:  /edit
    defaults: { _controller: SuperAdminInterfaceBundle:Object:edit }
    methods: [GET]
    
superadmin_interface_object_list:
    pattern:  /list
    defaults: { _controller: SuperAdminInterfaceBundle:Object:list }
    methods: [GET]